"""Add new columns to Post class

Revision ID: 103a70735dca
Revises: c6fb4aed8e6f
Create Date: 2019-09-23 12:26:43.884599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103a70735dca'
down_revision = 'c6fb4aed8e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.String(length=1500), nullable=False))
    op.drop_column('posts', 'post_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_img', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('posts', 'author')
    # ### end Alembic commands ###
