"""Add column to post_img

Revision ID: c6207ae916e5
Revises: 83977d5345c7
Create Date: 2019-09-23 10:03:12.410198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6207ae916e5'
down_revision = '83977d5345c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_img', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_img')
    # ### end Alembic commands ###
