"""Add new columns to Post class

Revision ID: c6fb4aed8e6f
Revises: c6207ae916e5
Create Date: 2019-09-23 10:27:01.992535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6fb4aed8e6f'
down_revision = 'c6207ae916e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.String(length=255), nullable=False))
    op.drop_constraint('posts_content_key', 'posts', type_='unique')
    op.drop_constraint('posts_title_key', 'posts', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('posts_title_key', 'posts', ['title'])
    op.create_unique_constraint('posts_content_key', 'posts', ['content'])
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###
