"""REmove unique constraint from class Comments

Revision ID: e0b86329e746
Revises: 103a70735dca
Create Date: 2019-09-23 22:41:32.851141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b86329e746'
down_revision = '103a70735dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_email_key', 'comments', type_='unique')
    op.drop_constraint('comments_name_key', 'comments', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('comments_name_key', 'comments', ['name'])
    op.create_unique_constraint('comments_email_key', 'comments', ['email'])
    # ### end Alembic commands ###
